version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: 'sampler-spa-dev'
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli

    build:
        commands:
            - echo Build started on `date`
            - ng build --prod

    post_build:
        commands:
            # clear S3 bucket
            - aws s3 rm s3://${S3_BUCKET} --recursive
            - echo S3 bucket cleared
            # copy files from dist folder into S3 bucket
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
