version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: 'mpr-rare-app'
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
            - echo Installing source Cypress dependencies...
            - apt-get update -y
            - apt-get install -y xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
    build:
        commands:
            - npm run testPhantom
            - npm run lint
            - npm run cy:run
            - echo Build started on `date`
            - ng build --prod --aot

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
